import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react"
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from '~/components/Sidebar'

import "~/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function GuestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen">
          <SessionProvider>
            <Sidebar />
            <main className="flex-1 p-8 bg-gray-100 overflow-y-auto">
              {children}
            </main>
          </SessionProvider>
        </div>
      </body>
    </html>
  );
}
